### ISSUE TITLE
Add some docs :)

### ISSUE THREAD

**Issue by camfindlay** [ServiceInnovationLab/ServiceRegistrationPipeline#10]
Please 👍

**Comment by camfindlay** [comment]
Some docs on good govt FOSS docs at https://www.ict.govt.nz/guidance-and-resources/open-government/new-zealand-government-open-access-and-licensing-nzgoal-framework/nzgoal-se/nzgoal-se-guidance-note-2/

**Comment by camfindlay** [comment]
Also a "getting started" section on how to actually get this running on a server would be helpful. eg, what version of python? how to run in a virtualenv? (or should we use pipenv?). etc etc. any ports needing to be opened etc?

**Comment by Br3nda** [comment]
i've added mention of `.python-version` to readme
