### ISSUE TITLE
Decrypt moves *.gpg into archive rather than actual file

### ISSUE THREAD

**Issue by camfindlay** [ServiceInnovationLab/ServiceRegistrationPipeline#24]
Currently it appears that https://github.com/ServiceInnovationLab/ServiceRegistrationPipeline/blob/master/decrypt.sh#L16 drops the *.gpg into the ./archive directory which means that it cant be used later by ./publish.py to compare for file differences. 

@Br3nda was this the intended action or should this be altered? Seems there is some first run priming you need to do to get a fresh version of this running.

**Comment by Br3nda** [comment]
Interesting. It's working on the server so I'll need to work out why.

**Comment by camfindlay** [comment]
I'm running gpg 2.2.8 on osx if that helps.
